

import { Inter, Quattrocento, Yellowtail, Montserrat, Bona_Nova, Noto_Sans_JP  } from 'next/font/google'
import './globals.css'
import Navbar from './_components/Navbar'
import SmoothScrolling from './_hooks/smoothScrolling'
import { LocaleProvider } from './_context/useLocale'
import { ModalProvider } from './_context/useModal'
import FooterNew from './_components/FooterNew'
import { CookiesProvider } from 'next-client-cookies/server';

const bonaNova = Bona_Nova({ subsets: ['latin'], weight: ['400', '700'], variable: "--font_bona_nova" })
const mont = Montserrat({
  subsets: ['latin'], weight: ['300', '400', '500', '700'],
  variable: "--font-mont"
})

const noto =  Noto_Sans_JP({subsets: ['latin'], weight: ['300', '400', '500', '700'], variable: "--font_noto"})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

const fetchData = async () => {
  "use server";
  const url = `${process.env.API_URL}/hotel?populate=*`
  console.log(url)
 


  
  let data = await fetch(url, {
      method: 'GET',
      headers: {
          'Content-Type': 'application/json'
      }
  }, {
      cache: 'no-cache'
  })

  let json = await data.json()
  return json.data;
}
export default async function RootLayout({ children }) {

  const data = await fetchData()
 
  let dates = {
    opening: data.attributes.openingDate,
    closing: data.attributes.closingDate
  }
  return (
    <html lang="en">
      <body className={`$${bonaNova.variant}  ${noto.variable}`}>
      <CookiesProvider>
        <LocaleProvider>
          <ModalProvider>
            <SmoothScrolling>
              <Navbar  dates={dates}/>
              {children}
              <FooterNew />
            </SmoothScrolling>
          </ModalProvider>
        </LocaleProvider>
        </CookiesProvider >
         

      </body>
    </html>
  )
}
